# Generated by Django 2.2.2 on 2019-06-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_wordtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=15, unique=True)),
                ('parmater_value', models.CharField(max_length=50)),
            ],
        ),
    ]
