# Generated by Django 2.2.2 on 2019-06-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_gameparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameparameters',
            old_name='parmater_value',
            new_name='parameter_value',
        ),
    ]
