# Generated by Django 2.2.2 on 2019-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20190612_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtype',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
